#logging:
#  level:
#    org.apache.coyote.http11.Http11InputBuffer: DEBUG # Incoming HTTP requests
#    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE # Outgoing http requests
#    org.springframework.jdbc.core: DEBUG # SQL

spring:
  datasource:
    url: jdbc:mysql://dispatchdelivery-db.cf8antsrmbzm.us-west-2.rds.amazonaws.com/dispatchDelivery?createDatabaseIfNotExist=true
    username: admin
    password: adminadmin
    driver-class-name: com.mysql.cj.jdbc.Driver
#  sql:
#    init:
#      mode: ${INIT_DB:always}
#      schema-locations: "classpath:database-init.sql"
#  jackson:
#    default-property-inclusion: non_null
#  cache:
#    caffeine:
#      spec: